name: Destroy back-end and front-end cloudformation stacks given a workflow ID.

on:
  workflow_call:
    inputs:
      workflow_id:
        required: true
        type: string
jobs:
  destroy-environment:
    runs-on: ubuntu-latest
    environment: production
    if: failure()
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Destroy environments
        run: |
          aws s3 rm s3://crc-${{inputs.workflow_id}} --recursive
          aws cloudformation delete-stack --stack-name crc-backend-${{inputs.workflow_id}}
          aws cloudformation delete-stack --stack-name crc-frontend-${{inputs.workflow_id}}
